---
- name: Installation PostgreSQL
  get_url:
    attr: "-O"
    dest: /usr/share/keyrings/postgresql.asc 
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add postgresql apt file
  shell: echo "deb [signed-by=/usr/share/keyrings/postgresql.asc] http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/postgresql.list 

- name: Create database postgresql
  postgresql_db:
    name: "{{ name_db }}"
  become: true
  become_user: postgres

- name: Create user postgresql
  postgresql_user:
    name: "{{ name_user }}"
    db: "{{ name_db }}"
  become: true
  become_user: postgres    

- name: Assign privileges
  postgresql_privs:
    database: "{{ name_db }}"
    roles: "{{ name_role }}"
    privs: ALL
    type: database
  become: true
  become_user: postgres 