---
- name: Copy Mastodon systemd service files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: /home/mastodon/live/dist/mastodon-sidekiq.service
      dest: /etc/systemd/system
    - src: /home/mastodon/live/dist/mastodon-streaming.service
      dest: /etc/systemd/system
    - src: /home/mastodon/live/dist/mastodon-web.service
      dest: /etc/systemd/system
  become: true
  become_user: mastodon     

- name: Enable Mastodon systemd sidekiq service
  systemd: 
    name: mastodon-sidekiq
    enabled: yes
  become: true
  become_user: mastodon

- name: Enable Mastodon systemd streaming service
  systemd: 
    name: mastodon-streaming
    enabled: yes
  become: true
  become_user: mastodon

- name: Enable Mastodon systemd web service
  systemd: 
    name: mastodon-web
    enabled: yes
  become: true
  become_user: mastodon  